set_property SEVERITY {warning} [get_drc_checks UCIO-1]
set_property SEVERITY {Warning} [get_drc_checks NSTD-1]
set_property PACKAGE_PIN AC18 [get_ports clk_p]
set_property IOSTANDARD LVDS [get_ports clk_p]

set_property PACKAGE_PIN W23 [get_ports {LED[7]}]
set_property PACKAGE_PIN AB26 [get_ports {LED[6]}]
set_property PACKAGE_PIN Y25 [get_ports {LED[5]}]
set_property PACKAGE_PIN AA23 [get_ports {LED[4]}]
set_property PACKAGE_PIN Y23 [get_ports {LED[3]}]
set_property PACKAGE_PIN Y22 [get_ports {LED[2]}]
set_property PACKAGE_PIN AE21 [get_ports {LED[1]}]
set_property PACKAGE_PIN AF24 [get_ports {LED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]

#set_property PACKAGE_PIN M24 [get_ports seg_clk]
#set_property PACKAGE_PIN L24 [get_ports seg_do]
#set_property PACKAGE_PIN R18 [get_ports seg_en]
#set_property IOSTANDARD LVCMOS33 [get_ports seg_clk]
#set_property IOSTANDARD LVCMOS33 [get_ports seg_do]
#set_property IOSTANDARD LVCMOS33 [get_ports seg_en]

set_property PACKAGE_PIN AA10 [get_ports {regnum[0]}]
set_property IOSTANDARD LVCMOS15 [get_ports {regnum[0]}]
set_property PACKAGE_PIN AB10 [get_ports {regnum[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {regnum[1]}]
set_property PACKAGE_PIN AA13 [get_ports {regnum[2]}]
set_property IOSTANDARD LVCMOS15 [get_ports {regnum[2]}]

set_property PACKAGE_PIN AF10 [get_ports reset]
#set_property PACKAGE_PIN AC16 [get_ports Clkin]
#set_property IOSTANDARD LVDS [get_ports Clkin]
set_property IOSTANDARD LVCMOS15 [get_ports reset]
#set_property PACKAGE_PIN W13 [get_ports reset]
#set_property IOSTANDARD LVCMOS18 [get_ports reset]